### PR TITLE
Add custom bk script

### PR DESCRIPTION
**Pull request by bondarau**

### CODE REVIEW

**Comment by bondarau** [comment]
Hello @anestos what do you think regarding this changes ?

**Comment by anestos** [comment]
Hey @bondarau what you have done so far is not bad in any way but if possible i would like to do the following instead:
Rename `CustomBackupConfig` to `postCommit` which can be an array of `scripts` with a `name`.
Put this under `configuration` so `configuration.postCommit`

```PostCommit:
    - name: custom-script-name
      script: |
        #!/bin/bash
        echo "Custom Script"
```
For each of those create a ConfigMap and in he admin deployment mount each config map seperately. 
That doesn't interfere with the default backup script (which we will update soon) and you should be able to have multiple post-commit scripts. 

Also add the new flag in the README on the table with all the values. 

Let me know what you think, if you don't have bandwidth i can take this over when i get some time

**Review by anestos — COMMENTED** [review]
This looks good, I will do some testing and approve/merge it.

**Review by anestos — APPROVED** [review]
I will move this to `curity.config.postCommitScripts` because `curity.config.configuration` has some more meaning for this helm-chart (namely if provided, the password is neither required nor included as an env variable if provided.

**Pull request merged**
