### PR TITLE
add configuration task for keystore conversion

### PR DESCRIPTION
**Pull request by bokristoffersson**
This PR add a configuration task for converting keystores and thus enable control over the ssl keys in the configuration from the Helm Chart. 

Example:
```   
convertKeystore: []
#      - sourceTls:
#          keyName: SSL_SERVER_KEY
#          fromSecretRef: curity-local-tls
#          cert: SSL_SERVER_CERT # optional
#          inAlias: curity
#          keystorePasswordSecretRef:
#            name: curity-idsvr-secret
#            key: KEYSTORE_PASSWORD
```

This will use the tls certificates from secret `curity-local-tls` and extract the key, put it in the environment variable `SSL_SERVER_KEY` that is used when starting the server. In this example also the `SSL_SERVER_CERT` will get populated.

### CODE REVIEW

**Comment by anestos** [comment]
This looks good but is it necessary? The same way you create secrets with the keys and store them in i.e `curity-local-tls` you can just create a secret with SSL_SERVER_KEY and SSL_SERVER_CERT and use `curity.config.environmentVariableSecrets`.

**Comment by bokristoffersson** [comment]
Agree. However with this configuration task the key administration would be fully automated. With OpenShift we are able to annotate a service to get trusted tls certificates in a secret that then can be used to convert to trusted keys and if we use that the _route_ service that Openshift creates (from the ingress) do not need any separate configuration.

**Comment by anestos** [comment]
Aha i see, that is OK then, can you only add the extra value in the readme ? then I can merge the PR and publish it with the next release on Monday

**Comment by bokristoffersson** [comment]
Thanks. That would be great.

**Review by anestos — APPROVED** [review]

**Pull request merged**
