### PR TITLE
[feature] Offer egress network policy to databases

### PR DESCRIPTION
**Pull request by marcmillien**
## Description

Add postgresql netpol egress in case we use netpol and postgresql as database

## Reference

https://curity.io/docs/idsvr/latest/system-admin-guide/data-sources/jdbc.html#postgresql-and-cockroachdb

### CODE REVIEW

**Comment by anestos** [comment]
I am a bit torn if this is a good fit for this helm chart. Curity is compatible with a large number of databases and adding specific templates for one of the will lead us in a rabbit-hole of adding more and it is going to be hard or even impossible to maintain. I ll leave this open for a while @marcmillien and we ll discuss internally.

**Comment by marcmillien** [comment]
>  Curity is compatible with a large number of databases and adding specific templates for one of the will lead us in a rabbit-hole of adding more and it is going to be hard or even impossible to maintain

Yes, I agree, maybe this PR needs to be completed or maybe adapted to be more agnostic.

I currently added postgresql as this is the database we use internally and this is the way I modified your chart to handle the access to our postgresql DB.

Do not hesitate to say if I can help :).

Maybe a solution could be something like:
```yaml
networkpolicy:
  enabled: true
  database:
    enabled: false
    port: ""
    cidr: []
```

Let's say if you want me to modify to this direction :).

>  I ll leave this open for a while @marcmillien and we ll discuss internally.

Sure :)

**Comment by marcmillien** [comment]
@anestos I added the commit to don't be database specific :).

**Comment by anestos** [comment]
> 

That looks better, but i have a question. Why did you add this netwrok policy on the admin node? 
The admin node doesn't communicate at all with the database, unless it also serves as a runtime node (which is not easily configurable in the helm chart anyway). I think we should remove that

**Comment by marcmillien** [comment]
> Why did you add this netwrok policy on the admin node?

To be honest I do not remember :D, maybe for the DB bootstrap?

**Comment by marcmillien** [comment]
In doubt, I remove it, I'll open a new PR if required next time we upgrade in our side :)

**Comment by marcmillien** [comment]
No news, I will reopen if required some days

**Pull request closed without merging**
